### ISSUE TITLE
Wrong placement with TugBoat

### ISSUE THREAD

**Issue by galou** [mwganson/MeshRemodel#47]
From the file linked in the [great announcement of TugBoat](https://forum.freecad.org/viewtopic.php?p=786366#p786366), I discovered a placement bug.

Steps to reproduce:
- Move `Cylinder001` to the origin with `TugBoat001` ("Haul commands" / "Haul Cylinder001")
- "Set Cylinder001 to identity placment" (note the typo from the original code)
- Pick destination of `TugBoat001` to `TugBoat004`
- Haul Cylinder001
- Notice that `Cylinder001`is not at `TugBoat004`

Version 1.10.28

**Comment by mwganson** [comment]
Thank you for testing and reporting your findings. 

The issue is with the file, not with the code.  I forgot to attach TugBoat001 to Cylinder001 and instead left it attached to Cylinder.  The first haul succeeds as expected because Cylinder and Cylinder001 are in the same location and orientation (even though their placement properties are different).  After the first move (Cylinder001 to the origin) instead of TugBoat001 remaining with Cylinder001 it gets pulled back to Cylinder due to the attachment.  The second move seemingly fails because the unexpected transformation is applied to Cylinder001.

The key to understanding how the TugBoat class works is this:  When the haul command is given the tugboat moves to the destination (calculates the transformation needed to move itself to the destination would be more accurate to say, but same result i the end).  It then applies this same transformation (translation and rotation) to the vessel it is hauling.  This is why Cylinder001 appears to have been given the wrong transformation.

Try this experiment to help illustrate the concept.  After moving Cylinder001 to the origin and after setting its internal placement ot the identity placement, in MeshRemodel create a line between the center of TugBoat001 and to some vertex on Cylinder001, then make a Compound in Part workbench (compound = Line + Cylinder001).  Change TugBoat001's Vessel from Cylinder001 to the new Compound.  Keep Destination as TugBoat004.  Do the Haul.  Note that now the Line that was centered on TugBioat001 is now connected to TugBoat004.

To further the tugboat analogy, you must pilot the tugboat out to the ship and latch on to it in order to haul that ship into the harbor.  The same is true with these virtual tugboats.  You must ensure the tugboat is located on the vessel to be hauled at the desired location and with the desired orientation before doing the haul.  I hope I have explained this properly.

**Comment by galou** [comment]
Thank your for the thorough explanations! Good job for the workbench in general, it's one of the few workbenches I use regularly, as a roboticist. I'll even write a wiki page on how to use TugBoats to move objects around  for the [CROSS workbench](https://github.com/galou/freecad.cross/) (when I find the time...).
